### PR TITLE
Updated so single word returns as list

### PR DESCRIPTION
**Pull request by teakettel**
I haven't actually run this to check if it works but I only had to add a few brackets so this should be fine

### CODE REVIEW

**Comment by TimKam** [comment]
Thanks for the PR! Looks good at first glance, but I'll need to think if I'm missing something. It would be nice if you could add a test.

**Comment by TimKam** [comment]
@teakettel could you allow me to edit this PR (push changes to your branch)? :-) See: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by teakettel** [comment]
Edits from maintainers were already allowed, but I removed them and then added them again in case something was off.

**Comment by TimKam** [comment]
Ok, then it was probably me doing something wrong. Thanks!

**Pull request merged**
